# This is a basic workflow to help you get started with Actions

name: GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      # Runs a set of commands using the runners shell
      - name: Build and Deploy
        env:
          NODE_ENV: production
          # Remove this line if you would like to skip using google analytics
          REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID_PATH }}
          REACT_APP_CV_URL: ${{ secrets.REACT_APP_CV_URL_PATH }}
          REACT_APP_PUBLIC_URL: ${{ secrets.REACT_APP_PUBLIC_URL_PATH }}
          # This is set automatically by github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/joorgelm/personal-site.git
          npm run deploy
