name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Build React
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        env:
          NODE_ENV: production
          REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID_PATH }}
          REACT_APP_CV_URL: ${{ secrets.REACT_APP_CV_URL_PATH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: build
          checkout: false
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
